version: "3.8"
services:
  sb-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "docker-app"
    ports:
      - 5000:8881
  mongodb:
    image: mongodb:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
networks:
  hospital_managment_system:
